### ISSUE TITLE
Onboarding/Build setup is difficult

### ISSUE THREAD

**Issue by heinermann** [neivv/teippi#1]
So after running `python waf config` and opening the thing in Visual Studio 2015 Community Edition, I encountered this.

```
1>------ Build started: Project: Teippi, Configuration: Release Win32 ------
1>  Waf: Entering directory `C:\Users\Adam\teippi\build'
1>  [ 1/49] Processing src/funcs.autogen: src\func\genfuncs.py src\func\nuottei.txt -> build\src\funcs.autogen
1>  Traceback (most recent call last):
1>
1>    File "..\src\func\genfuncs.py", line 265, in <module>
1>
1>      main()
1>
1>    File "..\src\func\genfuncs.py", line 260, in main
1>
1>      data = GenerateFuncs(nuottei, msvc_asm)
1>
1>    File "..\src\func\genfuncs.py", line 247, in GenerateFuncs
1>
1>      out += bytes(GenerateGccAsm(func), 'utf-8')
1>
1>  TypeError: str() takes at most 1 argument (2 given)
1>
1>
1>  Build failed
1>   -> task in 'src/funcs.autogen' failed (exit status 1):
1>      {task 35936496: src/funcs.autogen genfuncs.py,nuottei.txt -> funcs.autogen}
1>  ' python ..\\src\\func\\genfuncs.py ..\\src\\func\\nuottei.txt src\\funcs.autogen '
1>  Waf: Leaving directory `C:\Users\Adam\teippi\build'
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(37,5): error MSB3073: The command "python waf" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

So I assumed maybe it was looking for python3 and not python2, so I modified the script to directly point to my python3 executable, and I just get a different error, maybe because it's choosing a random compiler that cygwin installed.

```
1>------ Build started: Project: Teippi, Configuration: Release Win32 ------
1>  Waf: Entering directory `C:\Users\Adam\teippi\build'
1>  [ 1/49] Processing src/funcs.autogen: src\func\genfuncs.py src\func\nuottei.txt -> build\src\funcs.autogen
1>  [ 3/49] Compiling src\memory.cpp
1>  [ 5/49] Compiling src\perfclock.cpp
1>  [ 6/49] Compiling src\scthread.cpp
1>  In file included from ..\src\memory.cpp:1:0:
1>  ..\src\memory.h:33:28: error: declaration of 'operator new' as non-function
1>           void *operator new(size_t size) = delete;
1>
1>                              ^
1>  ..\src\memory.h:33:24: error: expected ';' at end of member declaration
1>           void *operator new(size_t size) = delete;
1>
1>                          ^
1>  ..\src\memory.h:33:35: error: expected ')' before 'size'
1>           void *operator new(size_t size) = delete;
1>
1>                                     ^
1>  ..\src\memory.h:34:30: error: declaration of 'operator new []' as non-function
1>           void *operator new[](size_t size) = delete;
1>
1>                                ^
1>  ..\src\memory.h:34:28: error: expected ';' at end of member declaration
1>           void *operator new[](size_t size) = delete;
1>
1>                              ^
1>  ..\src\memory.h:34:37: error: expected ')' before 'size'
1>           void *operator new[](size_t size) = delete;
1>
1>                                       ^
1>
1>  In file included from /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/random:49:0,
1>                   from /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/stl_algo.h:66,
1>                   from /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/algorithm:62,
1>                   from ..\src\common/iter.h:3,
1>                   from ..\src\types.h:5,
1>                   from ..\src\thread.h:10,
1>                   from ..\src\scthread.h:4,
1>                   from ..\src\scthread.cpp:1:
1>  /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/bits/random.h:106:26: error: expected unqualified-id before '__int128'
1>         { typedef unsigned __int128 type; };
1>                            ^
1>
1>  Waf: Leaving directory `C:\Users\Adam\teippi\build'
1>  Build failed
1>   -> task in 'obj' failed (exit status 1):
1>      {task 36052464: cxx memory.cpp -> memory.cpp.3.o}
1>  ['C:\\cygwin64\\bin\\g++.exe', '-m32', '-march=i686', '-Wall', '-g', '-O3', '--std=c++14', '-Wno-sign-compare', '-Wno-format', '-ffunction-sections', '-fdata-sections', '-fno-exceptions', '-IC:\\Users\\Adam\\teippi\\build\\src', '..\\src\\memory.cpp', '-c', '-o', 'C:\\Users\\Adam\\teippi\\build\\src\\memory.cpp.3.o']
1>   -> task in 'obj' failed (exit status 1):
1>      {task 36118672: cxx scthread.cpp -> scthread.cpp.3.o}
1>  ['C:\\cygwin64\\bin\\g++.exe', '-m32', '-march=i686', '-Wall', '-g', '-O3', '--std=c++14', '-Wno-sign-compare', '-Wno-format', '-ffunction-sections', '-fdata-sections', '-fno-exceptions', '-IC:\\Users\\Adam\\teippi\\build\\src', '..\\src\\scthread.cpp', '-c', '-o', 'C:\\Users\\Adam\\teippi\\build\\src\\scthread.cpp.3.o']
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(37,5): error MSB3073: The command "python waf" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

funcs.autogen wasn't being created so I went and ran `python3.4m genfuncs.py nuottei.txt funcs.autogen --msvc` from the funcs directory and copied funcs.autogen over to src.

It went downhill from here, so I decided I would just reconfigure everything to work directly with VC++2015, including compiling the freetype dependency. The Chaoslauncher functions were missing so I had to comment that out and just use the MPQDraft plugin. After testing though, it appeared to work, then froze.

So I'm not sure how to set up now.

**Comment by neivv** [comment]
Ah, I did not realize that the build script would break with python2 being default installation or it finding some cygwin compiler.

I think using "py -3" in the script would fix the python issue, the incompatible compiler one may be harder to detect.
I'll remove the code which makes the compiler detection to dislike msvc - it was relevant back when msvc didn't work.
The build script can be forced to use msvc with --check-cxx-compiler=msvc argument to configure, if you wish to try using it.

The chaoslauncher functions were missing? Was that just because src\bwlauncher.cpp was not included in the project file or something worse?

For the freeze: Could you please try building with the build script - if you can get it work. The code is fragile in a way that it requires some .cpp files use exceptions and others to explicitly not have them (might not actually be issue with visual studio) . Or just configure the files file-by-file.
But if it froze, it should generate stack dumps of the main thread to file named freeze.log Starcraft's error directory. I would like to have look at the log.

**Comment by heinermann** [comment]
Yeah the bwlauncher.cpp was missing from the VS project. I'm currently trying to debug the issues with VS.

**Comment by neivv** [comment]
Actually building the bwlauncher.cpp in visual studio causes an error as it includes windows.h, which defines min/max macros

**Comment by heinermann** [comment]
I've dealt with that by defining the NOMINMAX macro, which disables those. There was a startup crash with a debug build that caused a crash, likely because of the `Debug Information Format` option, changing it to `Program Database (/Zi)` fixed that.

I injected BWAPI's debug build along with it so that BWAPI's top level exception handler can assist the debugging process by looking up pdb information.

```
//////////////////////////////////////////////////
TIME: Sun Aug 30 14:59:20 2015

VERSION: 1.16.1.1
BWAPI:
  REVISION: 4708
  BUILD: DEBUG
  ERROR: Unit_Does_Not_Exist
  LOCATION: Single Player 

EXCEPTION: 0xC0000005    EXCEPTION_ACCESS_VIOLATION
FAULT:     0x6D47E67E    Teippi.bwl
REGISTERS:
  EDI: 00189F0C
  ESI: 000003E7
  EBX: 00000000
  EDX: 00000000
  ECX: CCCCCCCC
  EAX: 00000000
  EBP: 00189F0C
  EIP: 6D47E67E
  ESP: 00189CAC
STACK:
  Teippi.bwl        0x6D47E67E    LoadGrp
                                     c:\users\adam\teippi\src\init.cpp:123
  Teippi.bwl        0x6D485CF4    LoadGrp_Hook
                                     c:\users\adam\teippi\src\limits.cpp:628
  StarCraft.exe     0x0047AEA8    loadImagesData_lowMem
  StarCraft.exe     0x004D7276    LoadImageData
  StarCraft.exe     0x004D749C    loadInitIscriptBIN
  StarCraft.exe     0x004E08FC    StarMain
  StarCraft.exe     0x004E0B20    WinMain(x,x,x,x)
  StarCraft.exe     0x00404DA5    start
  KERNEL32.DLL      0x76CD7C04    BaseThreadInitThunk
  ntdll.dll         0x76F2AD1F    RtlInitializeExceptionChain
  ntdll.dll         0x76F2ACEA    RtlInitializeExceptionChain
```

**Comment by neivv** [comment]
It tries to load image 0x3e7? Also why loadImagesData_lowMem? Are you intentionally using the registry setting for lowmem graphics?

**Comment by heinermann** [comment]
No, I probably just gave it a bad function name. I got past the above by changing compiler options anyway. Now crashing on game start. It seems the compiler is overriding some registers that you assume are available, i.e.

![screenshot from 2015-08-30 15 17 47](https://cloud.githubusercontent.com/assets/1966366/9569792/7b756c74-4f2a-11e5-9079-7c0503475a02.png)

This particular function can be turned into a __thiscall. Otherwise, making assumptions isn't a very safe way to hook.

**Comment by neivv** [comment]
So this seems to be the compiler initializing some of the data with debug pattern? It certainly does not do that on my pc, is it some flag that can be turned off? 
The files that include those functions must not have any kind of "hidden" commands at the start of the function, that's why the exceptions are only partially enabled, profiling info generation won't work and so on.
This one hook can certainly be turned to __thiscall, but how about hook of a function that  takes its arguments in eax, edi, and ebx?
The _correct_ solution would be to have some kind of assembly hook wrapper autogeneration, which would never be touched by the compiler, but that would be more work than just disabling compiler settings.

**Comment by heinermann** [comment]
When I was trying to make BWAPI hooks more safer a long time ago I would just rewrite the function and hook one level up. I'll see what I can do.

**Comment by neivv** [comment]
The "debug pattern filling" seems to be caused by option `/RTCs`. The option `/GS` seems to also cause problems when used with the hook code.

**Comment by heinermann** [comment]
I finally got it working. I created a branch here which is exclusive to MSVC: https://github.com/heinermann/teippi/tree/msvc-strict

That is, a new person with a new computer should be able to install VS2015, download the source, hit compile and it should work.

**Comment by neivv** [comment]
Ha, finally got completely rid of compiler-specific assembly and preprocessing scripts.

The project should now build with any kinds of compiler/debug/profiling settings, exceptions can be enabled for every file, and there is _a real_ VS15 project file that can be used =)
