### ISSUE TITLE
Porting changes to Diablo II 1.10f/1.14

### ISSUE THREAD

**Issue by DoctorGoat** [neivv/teippi#3]
Pardon me,

I'm not familiar with Rust, though I probably should be. I've been wrestling with the sprite caches in Diablo II and I'm interested in what I'm seeing here. 

Would you be willing to help any with this? 1.10f is vastly more interesting, but I'm not going to turn down any help. If you need any dumps/information, just ask.

**Comment by neivv** [comment]
Sorry, there is no overlap at all between Starcraft 1 and Diablo 2 sprite rendering.

(And considering that the project is C++ so I feel that you may have opened the issue on a wrong repo?)

**Comment by DoctorGoat** [comment]
Yeah, my apologies. I was looking at the more bullets plugin and the other plugins and hadn't slept much. I wrote that request and then fell asleep during a Youtube video, and I'm just now waking up.
